language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
before_install:
    - pip install pipenv
    - pipenv install --dev --skip-lock
script:
    - pipenv run codespell -L paket --skip=./textstat/resources/*/easy_words.txt
    - pipenv run flake8 .
    - pipenv run pytest test.py
