language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
before_install:
    - pip install pipenv
    - pipenv install --dev --skip-lock
    - pip install codespell flake8
script:
    - codespell
    - pipenv run pycodestyle textstat/
    - pipenv run pycodestyle test.py
    - flake8 .
    - pipenv run pytest test.py
