language: python
python:
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
before_install:
    - pip install pipenv
    - pipenv install --dev --skip-lock
script:
    - pipenv run pycodestyle textstat/
    - pipenv run pycodestyle test.py
    - pipenv run pytest test.py
